// This file is auto-generated by @hey-api/openapi-ts
import { z } from 'zod';

export const zAddress = z.union([
  z.object({
    city: z.string(),
    country: z.string(),
    createdAt: z.iso.datetime(),
    id: z.uuid(),
    lineOne: z.string(),
    lineTwo: z.union([z.string(), z.null()]),
    province: z.string(),
    updatedAt: z.iso.datetime(),
    zipCode: z.string(),
  }),
  z.null(),
]);

export const zAddresses = z.array(
  z.union([
    z.object({
      city: z.string(),
      country: z.string(),
      createdAt: z.iso.datetime(),
      id: z.uuid(),
      lineOne: z.string(),
      lineTwo: z.union([z.string(), z.null()]),
      province: z.string(),
      updatedAt: z.iso.datetime(),
      zipCode: z.string(),
    }),
    z.null(),
  ])
);

export const zBankDetail = z.union([
  z.object({
    accountHolder: z.string(),
    accountNumber: z.string(),
    bankName: z.string(),
    branchName: z.string(),
    createdAt: z.iso.datetime(),
    id: z.uuid(),
    updatedAt: z.iso.datetime(),
  }),
  z.null(),
]);

export const zBankDetails = z.array(
  z.union([
    z.object({
      accountHolder: z.string(),
      accountNumber: z.string(),
      bankName: z.string(),
      branchName: z.string(),
      createdAt: z.iso.datetime(),
      id: z.uuid(),
      updatedAt: z.iso.datetime(),
    }),
    z.null(),
  ])
);

export const zCollection = z.object({
  collector: z.object({
    activeOrganization: z.uuid(),
    address: z.union([
      z.object({
        city: z.string(),
        country: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        lineOne: z.string(),
        lineTwo: z.union([z.string(), z.null()]),
        province: z.string(),
        updatedAt: z.iso.datetime(),
        zipCode: z.string(),
      }),
      z.null(),
    ]),
    banReason: z.union([z.string(), z.null()]),
    bankDetails: z.union([
      z.object({
        accountHolder: z.string(),
        accountNumber: z.string(),
        bankName: z.string(),
        branchName: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        updatedAt: z.iso.datetime(),
      }),
      z.null(),
    ]),
    banned: z.boolean(),
    createdAt: z.iso.datetime(),
    email: z.string(),
    id: z.uuid(),
    mfaEnabled: z.boolean(),
    mfaVerified: z.boolean(),
    name: z.string(),
    phone: z.string(),
    roles: z.array(
      z.object({
        createdAt: z.iso.datetime(),
        description: z.union([z.string(), z.null()]),
        id: z.uuid(),
        name: z.string(),
        permissions: z.array(z.string()),
        updatedAt: z.iso.datetime(),
      })
    ),
    type: z.enum(['standard', 'collector', 'business', 'system']),
    updatedAt: z.iso.datetime(),
  }),
  createdAt: z.iso.datetime(),
  id: z.uuid(),
  materials: z.array(
    z.object({
      createdAt: z.iso.datetime(),
      id: z.uuid(),
      material: z.object({
        carbonFactor: z.string(),
        createdAt: z.iso.datetime(),
        gwCode: z.string(),
        id: z.uuid(),
        name: z.string(),
        updatedAt: z.iso.datetime(),
        value: z.number(),
      }),
      updatedAt: z.iso.datetime(),
      weight: z.number(),
    })
  ),
  organization: z.object({
    address: z.union([
      z.object({
        city: z.string(),
        country: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        lineOne: z.string(),
        lineTwo: z.union([z.string(), z.null()]),
        province: z.string(),
        updatedAt: z.iso.datetime(),
        zipCode: z.string(),
      }),
      z.null(),
    ]),
    bankDetails: z.union([
      z.object({
        accountHolder: z.string(),
        accountNumber: z.string(),
        bankName: z.string(),
        branchName: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        updatedAt: z.iso.datetime(),
      }),
      z.null(),
    ]),
    createdAt: z.iso.datetime(),
    id: z.uuid(),
    name: z.string(),
    updatedAt: z.iso.datetime(),
  }),
  updatedAt: z.iso.datetime(),
});

export const zCollections = z.array(
  z.object({
    collector: z.object({
      activeOrganization: z.uuid(),
      address: z.union([
        z.object({
          city: z.string(),
          country: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          lineOne: z.string(),
          lineTwo: z.union([z.string(), z.null()]),
          province: z.string(),
          updatedAt: z.iso.datetime(),
          zipCode: z.string(),
        }),
        z.null(),
      ]),
      banReason: z.union([z.string(), z.null()]),
      bankDetails: z.union([
        z.object({
          accountHolder: z.string(),
          accountNumber: z.string(),
          bankName: z.string(),
          branchName: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          updatedAt: z.iso.datetime(),
        }),
        z.null(),
      ]),
      banned: z.boolean(),
      createdAt: z.iso.datetime(),
      email: z.string(),
      id: z.uuid(),
      mfaEnabled: z.boolean(),
      mfaVerified: z.boolean(),
      name: z.string(),
      phone: z.string(),
      roles: z.array(
        z.object({
          createdAt: z.iso.datetime(),
          description: z.union([z.string(), z.null()]),
          id: z.uuid(),
          name: z.string(),
          permissions: z.array(z.string()),
          updatedAt: z.iso.datetime(),
        })
      ),
      type: z.enum(['standard', 'collector', 'business', 'system']),
      updatedAt: z.iso.datetime(),
    }),
    createdAt: z.iso.datetime(),
    id: z.uuid(),
    materials: z.array(
      z.object({
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        material: z.object({
          carbonFactor: z.string(),
          createdAt: z.iso.datetime(),
          gwCode: z.string(),
          id: z.uuid(),
          name: z.string(),
          updatedAt: z.iso.datetime(),
          value: z.number(),
        }),
        updatedAt: z.iso.datetime(),
        weight: z.number(),
      })
    ),
    organization: z.object({
      address: z.union([
        z.object({
          city: z.string(),
          country: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          lineOne: z.string(),
          lineTwo: z.union([z.string(), z.null()]),
          province: z.string(),
          updatedAt: z.iso.datetime(),
          zipCode: z.string(),
        }),
        z.null(),
      ]),
      bankDetails: z.union([
        z.object({
          accountHolder: z.string(),
          accountNumber: z.string(),
          bankName: z.string(),
          branchName: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          updatedAt: z.iso.datetime(),
        }),
        z.null(),
      ]),
      createdAt: z.iso.datetime(),
      id: z.uuid(),
      name: z.string(),
      updatedAt: z.iso.datetime(),
    }),
    updatedAt: z.iso.datetime(),
  })
);

export const zErrorResponse = z.object({
  error: z.optional(z.string()).default('Bad Request'),
  message: z
    .optional(z.string())
    .default(
      'The request could not be understood or was missing required parameters.'
    ),
});

export const zLoginPayload = z.object({
  emailOrPhone: z.email(),
  password: z.string().min(6).max(100),
});

export const zMaterial = z.object({
  carbonFactor: z.string(),
  createdAt: z.iso.datetime(),
  gwCode: z.string(),
  id: z.uuid(),
  name: z.string(),
  updatedAt: z.iso.datetime(),
  value: z.number(),
});

export const zMaterials = z.array(
  z.object({
    carbonFactor: z.string(),
    createdAt: z.iso.datetime(),
    gwCode: z.string(),
    id: z.uuid(),
    name: z.string(),
    updatedAt: z.iso.datetime(),
    value: z.number(),
  })
);

export const zMfaVerifyPayload = z.object({
  code: z.optional(z.string()),
});

export const zOrganization = z.object({
  address: z.union([
    z.object({
      city: z.string(),
      country: z.string(),
      createdAt: z.iso.datetime(),
      id: z.uuid(),
      lineOne: z.string(),
      lineTwo: z.union([z.string(), z.null()]),
      province: z.string(),
      updatedAt: z.iso.datetime(),
      zipCode: z.string(),
    }),
    z.null(),
  ]),
  bankDetails: z.union([
    z.object({
      accountHolder: z.string(),
      accountNumber: z.string(),
      bankName: z.string(),
      branchName: z.string(),
      createdAt: z.iso.datetime(),
      id: z.uuid(),
      updatedAt: z.iso.datetime(),
    }),
    z.null(),
  ]),
  createdAt: z.iso.datetime(),
  id: z.uuid(),
  name: z.string(),
  updatedAt: z.iso.datetime(),
});

export const zOrganizations = z.array(
  z.object({
    address: z.union([
      z.object({
        city: z.string(),
        country: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        lineOne: z.string(),
        lineTwo: z.union([z.string(), z.null()]),
        province: z.string(),
        updatedAt: z.iso.datetime(),
        zipCode: z.string(),
      }),
      z.null(),
    ]),
    bankDetails: z.union([
      z.object({
        accountHolder: z.string(),
        accountNumber: z.string(),
        bankName: z.string(),
        branchName: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        updatedAt: z.iso.datetime(),
      }),
      z.null(),
    ]),
    createdAt: z.iso.datetime(),
    id: z.uuid(),
    name: z.string(),
    updatedAt: z.iso.datetime(),
  })
);

export const zRole = z.object({
  createdAt: z.iso.datetime(),
  description: z.union([z.string(), z.null()]),
  id: z.uuid(),
  name: z.string(),
  permissions: z.array(z.string()),
  updatedAt: z.iso.datetime(),
});

export const zRoles = z.array(
  z.object({
    createdAt: z.iso.datetime(),
    description: z.union([z.string(), z.null()]),
    id: z.uuid(),
    name: z.string(),
    permissions: z.array(z.string()),
    updatedAt: z.iso.datetime(),
  })
);

export const zSignUpPayload = z.object({
  email: z.optional(z.email()),
  name: z.string().min(2).max(100),
  password: z.string().min(6).max(100),
  phone: z.optional(z.string().min(10).max(15)),
});

export const zSuccessResponse = z.object({
  item: z.optional(
    z.union([
      z.object({
        activeOrganization: z.uuid(),
        address: z.union([
          z.object({
            city: z.string(),
            country: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            lineOne: z.string(),
            lineTwo: z.union([z.string(), z.null()]),
            province: z.string(),
            updatedAt: z.iso.datetime(),
            zipCode: z.string(),
          }),
          z.null(),
        ]),
        banReason: z.union([z.string(), z.null()]),
        bankDetails: z.union([
          z.object({
            accountHolder: z.string(),
            accountNumber: z.string(),
            bankName: z.string(),
            branchName: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            updatedAt: z.iso.datetime(),
          }),
          z.null(),
        ]),
        banned: z.boolean(),
        createdAt: z.iso.datetime(),
        email: z.string(),
        id: z.uuid(),
        mfaEnabled: z.boolean(),
        mfaVerified: z.boolean(),
        name: z.string(),
        phone: z.string(),
        roles: z.array(
          z.object({
            createdAt: z.iso.datetime(),
            description: z.union([z.string(), z.null()]),
            id: z.uuid(),
            name: z.string(),
            permissions: z.array(z.string()),
            updatedAt: z.iso.datetime(),
          })
        ),
        type: z.enum(['standard', 'collector', 'business', 'system']),
        updatedAt: z.iso.datetime(),
      }),
      z.object({
        createdAt: z.iso.datetime(),
        description: z.union([z.string(), z.null()]),
        id: z.uuid(),
        name: z.string(),
        permissions: z.array(z.string()),
        updatedAt: z.iso.datetime(),
      }),
      z.object({
        address: z.union([
          z.object({
            city: z.string(),
            country: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            lineOne: z.string(),
            lineTwo: z.union([z.string(), z.null()]),
            province: z.string(),
            updatedAt: z.iso.datetime(),
            zipCode: z.string(),
          }),
          z.null(),
        ]),
        bankDetails: z.union([
          z.object({
            accountHolder: z.string(),
            accountNumber: z.string(),
            bankName: z.string(),
            branchName: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            updatedAt: z.iso.datetime(),
          }),
          z.null(),
        ]),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        name: z.string(),
        updatedAt: z.iso.datetime(),
      }),
      z.union([
        z.object({
          city: z.string(),
          country: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          lineOne: z.string(),
          lineTwo: z.union([z.string(), z.null()]),
          province: z.string(),
          updatedAt: z.iso.datetime(),
          zipCode: z.string(),
        }),
        z.null(),
      ]),
      z.union([
        z.object({
          accountHolder: z.string(),
          accountNumber: z.string(),
          bankName: z.string(),
          branchName: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          updatedAt: z.iso.datetime(),
        }),
        z.null(),
      ]),
      z.object({
        carbonFactor: z.string(),
        createdAt: z.iso.datetime(),
        gwCode: z.string(),
        id: z.uuid(),
        name: z.string(),
        updatedAt: z.iso.datetime(),
        value: z.number(),
      }),
      z.object({
        collector: z.object({
          activeOrganization: z.uuid(),
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          banReason: z.union([z.string(), z.null()]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          banned: z.boolean(),
          createdAt: z.iso.datetime(),
          email: z.string(),
          id: z.uuid(),
          mfaEnabled: z.boolean(),
          mfaVerified: z.boolean(),
          name: z.string(),
          phone: z.string(),
          roles: z.array(
            z.object({
              createdAt: z.iso.datetime(),
              description: z.union([z.string(), z.null()]),
              id: z.uuid(),
              name: z.string(),
              permissions: z.array(z.string()),
              updatedAt: z.iso.datetime(),
            })
          ),
          type: z.enum(['standard', 'collector', 'business', 'system']),
          updatedAt: z.iso.datetime(),
        }),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        materials: z.array(
          z.object({
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            material: z.object({
              carbonFactor: z.string(),
              createdAt: z.iso.datetime(),
              gwCode: z.string(),
              id: z.uuid(),
              name: z.string(),
              updatedAt: z.iso.datetime(),
              value: z.number(),
            }),
            updatedAt: z.iso.datetime(),
            weight: z.number(),
          })
        ),
        organization: z.object({
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          name: z.string(),
          updatedAt: z.iso.datetime(),
        }),
        updatedAt: z.iso.datetime(),
      }),
      z.object({
        collector: z.object({
          activeOrganization: z.uuid(),
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          banReason: z.union([z.string(), z.null()]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          banned: z.boolean(),
          createdAt: z.iso.datetime(),
          email: z.string(),
          id: z.uuid(),
          mfaEnabled: z.boolean(),
          mfaVerified: z.boolean(),
          name: z.string(),
          phone: z.string(),
          roles: z.array(
            z.object({
              createdAt: z.iso.datetime(),
              description: z.union([z.string(), z.null()]),
              id: z.uuid(),
              name: z.string(),
              permissions: z.array(z.string()),
              updatedAt: z.iso.datetime(),
            })
          ),
          type: z.enum(['standard', 'collector', 'business', 'system']),
          updatedAt: z.iso.datetime(),
        }),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        materials: z.array(
          z.object({
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            material: z.object({
              carbonFactor: z.string(),
              createdAt: z.iso.datetime(),
              gwCode: z.string(),
              id: z.uuid(),
              name: z.string(),
              updatedAt: z.iso.datetime(),
              value: z.number(),
            }),
            updatedAt: z.iso.datetime(),
            weight: z.number(),
          })
        ),
        organization: z.object({
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          name: z.string(),
          updatedAt: z.iso.datetime(),
        }),
        updatedAt: z.iso.datetime(),
      }),
    ])
  ),
  items: z.optional(
    z.union([
      z.array(
        z.object({
          activeOrganization: z.uuid(),
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          banReason: z.union([z.string(), z.null()]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          banned: z.boolean(),
          createdAt: z.iso.datetime(),
          email: z.string(),
          id: z.uuid(),
          mfaEnabled: z.boolean(),
          mfaVerified: z.boolean(),
          name: z.string(),
          phone: z.string(),
          roles: z.array(
            z.object({
              createdAt: z.iso.datetime(),
              description: z.union([z.string(), z.null()]),
              id: z.uuid(),
              name: z.string(),
              permissions: z.array(z.string()),
              updatedAt: z.iso.datetime(),
            })
          ),
          type: z.enum(['standard', 'collector', 'business', 'system']),
          updatedAt: z.iso.datetime(),
        })
      ),
      z.array(
        z.object({
          createdAt: z.iso.datetime(),
          description: z.union([z.string(), z.null()]),
          id: z.uuid(),
          name: z.string(),
          permissions: z.array(z.string()),
          updatedAt: z.iso.datetime(),
        })
      ),
      z.array(
        z.object({
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          name: z.string(),
          updatedAt: z.iso.datetime(),
        })
      ),
      z.array(
        z.union([
          z.object({
            city: z.string(),
            country: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            lineOne: z.string(),
            lineTwo: z.union([z.string(), z.null()]),
            province: z.string(),
            updatedAt: z.iso.datetime(),
            zipCode: z.string(),
          }),
          z.null(),
        ])
      ),
      z.array(
        z.union([
          z.object({
            accountHolder: z.string(),
            accountNumber: z.string(),
            bankName: z.string(),
            branchName: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            updatedAt: z.iso.datetime(),
          }),
          z.null(),
        ])
      ),
      z.array(
        z.object({
          carbonFactor: z.string(),
          createdAt: z.iso.datetime(),
          gwCode: z.string(),
          id: z.uuid(),
          name: z.string(),
          updatedAt: z.iso.datetime(),
          value: z.number(),
        })
      ),
      z.array(
        z.object({
          collector: z.object({
            activeOrganization: z.uuid(),
            address: z.union([
              z.object({
                city: z.string(),
                country: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                lineOne: z.string(),
                lineTwo: z.union([z.string(), z.null()]),
                province: z.string(),
                updatedAt: z.iso.datetime(),
                zipCode: z.string(),
              }),
              z.null(),
            ]),
            banReason: z.union([z.string(), z.null()]),
            bankDetails: z.union([
              z.object({
                accountHolder: z.string(),
                accountNumber: z.string(),
                bankName: z.string(),
                branchName: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                updatedAt: z.iso.datetime(),
              }),
              z.null(),
            ]),
            banned: z.boolean(),
            createdAt: z.iso.datetime(),
            email: z.string(),
            id: z.uuid(),
            mfaEnabled: z.boolean(),
            mfaVerified: z.boolean(),
            name: z.string(),
            phone: z.string(),
            roles: z.array(
              z.object({
                createdAt: z.iso.datetime(),
                description: z.union([z.string(), z.null()]),
                id: z.uuid(),
                name: z.string(),
                permissions: z.array(z.string()),
                updatedAt: z.iso.datetime(),
              })
            ),
            type: z.enum(['standard', 'collector', 'business', 'system']),
            updatedAt: z.iso.datetime(),
          }),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          materials: z.array(
            z.object({
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              material: z.object({
                carbonFactor: z.string(),
                createdAt: z.iso.datetime(),
                gwCode: z.string(),
                id: z.uuid(),
                name: z.string(),
                updatedAt: z.iso.datetime(),
                value: z.number(),
              }),
              updatedAt: z.iso.datetime(),
              weight: z.number(),
            })
          ),
          organization: z.object({
            address: z.union([
              z.object({
                city: z.string(),
                country: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                lineOne: z.string(),
                lineTwo: z.union([z.string(), z.null()]),
                province: z.string(),
                updatedAt: z.iso.datetime(),
                zipCode: z.string(),
              }),
              z.null(),
            ]),
            bankDetails: z.union([
              z.object({
                accountHolder: z.string(),
                accountNumber: z.string(),
                bankName: z.string(),
                branchName: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                updatedAt: z.iso.datetime(),
              }),
              z.null(),
            ]),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            name: z.string(),
            updatedAt: z.iso.datetime(),
          }),
          updatedAt: z.iso.datetime(),
        })
      ),
      z.array(
        z.object({
          collector: z.object({
            activeOrganization: z.uuid(),
            address: z.union([
              z.object({
                city: z.string(),
                country: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                lineOne: z.string(),
                lineTwo: z.union([z.string(), z.null()]),
                province: z.string(),
                updatedAt: z.iso.datetime(),
                zipCode: z.string(),
              }),
              z.null(),
            ]),
            banReason: z.union([z.string(), z.null()]),
            bankDetails: z.union([
              z.object({
                accountHolder: z.string(),
                accountNumber: z.string(),
                bankName: z.string(),
                branchName: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                updatedAt: z.iso.datetime(),
              }),
              z.null(),
            ]),
            banned: z.boolean(),
            createdAt: z.iso.datetime(),
            email: z.string(),
            id: z.uuid(),
            mfaEnabled: z.boolean(),
            mfaVerified: z.boolean(),
            name: z.string(),
            phone: z.string(),
            roles: z.array(
              z.object({
                createdAt: z.iso.datetime(),
                description: z.union([z.string(), z.null()]),
                id: z.uuid(),
                name: z.string(),
                permissions: z.array(z.string()),
                updatedAt: z.iso.datetime(),
              })
            ),
            type: z.enum(['standard', 'collector', 'business', 'system']),
            updatedAt: z.iso.datetime(),
          }),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          materials: z.array(
            z.object({
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              material: z.object({
                carbonFactor: z.string(),
                createdAt: z.iso.datetime(),
                gwCode: z.string(),
                id: z.uuid(),
                name: z.string(),
                updatedAt: z.iso.datetime(),
                value: z.number(),
              }),
              updatedAt: z.iso.datetime(),
              weight: z.number(),
            })
          ),
          organization: z.object({
            address: z.union([
              z.object({
                city: z.string(),
                country: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                lineOne: z.string(),
                lineTwo: z.union([z.string(), z.null()]),
                province: z.string(),
                updatedAt: z.iso.datetime(),
                zipCode: z.string(),
              }),
              z.null(),
            ]),
            bankDetails: z.union([
              z.object({
                accountHolder: z.string(),
                accountNumber: z.string(),
                bankName: z.string(),
                branchName: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                updatedAt: z.iso.datetime(),
              }),
              z.null(),
            ]),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            name: z.string(),
            updatedAt: z.iso.datetime(),
          }),
          updatedAt: z.iso.datetime(),
        })
      ),
    ])
  ),
  pageDetails: z.optional(
    z.union([
      z.object({
        count: z.optional(z.int().gte(0)),
        currentPage: z.optional(z.int().gte(1)),
        nextPage: z.optional(z.int().gte(2)),
        pages: z.optional(z.int().gte(0)),
        previousPage: z.optional(z.int().gte(1)),
      }),
      z.null(),
    ])
  ),
});

export const zTransaction = z.object({
  collector: z.object({
    activeOrganization: z.uuid(),
    address: z.union([
      z.object({
        city: z.string(),
        country: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        lineOne: z.string(),
        lineTwo: z.union([z.string(), z.null()]),
        province: z.string(),
        updatedAt: z.iso.datetime(),
        zipCode: z.string(),
      }),
      z.null(),
    ]),
    banReason: z.union([z.string(), z.null()]),
    bankDetails: z.union([
      z.object({
        accountHolder: z.string(),
        accountNumber: z.string(),
        bankName: z.string(),
        branchName: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        updatedAt: z.iso.datetime(),
      }),
      z.null(),
    ]),
    banned: z.boolean(),
    createdAt: z.iso.datetime(),
    email: z.string(),
    id: z.uuid(),
    mfaEnabled: z.boolean(),
    mfaVerified: z.boolean(),
    name: z.string(),
    phone: z.string(),
    roles: z.array(
      z.object({
        createdAt: z.iso.datetime(),
        description: z.union([z.string(), z.null()]),
        id: z.uuid(),
        name: z.string(),
        permissions: z.array(z.string()),
        updatedAt: z.iso.datetime(),
      })
    ),
    type: z.enum(['standard', 'collector', 'business', 'system']),
    updatedAt: z.iso.datetime(),
  }),
  createdAt: z.iso.datetime(),
  id: z.uuid(),
  materials: z.array(
    z.object({
      createdAt: z.iso.datetime(),
      id: z.uuid(),
      material: z.object({
        carbonFactor: z.string(),
        createdAt: z.iso.datetime(),
        gwCode: z.string(),
        id: z.uuid(),
        name: z.string(),
        updatedAt: z.iso.datetime(),
        value: z.number(),
      }),
      updatedAt: z.iso.datetime(),
      weight: z.number(),
    })
  ),
  organization: z.object({
    address: z.union([
      z.object({
        city: z.string(),
        country: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        lineOne: z.string(),
        lineTwo: z.union([z.string(), z.null()]),
        province: z.string(),
        updatedAt: z.iso.datetime(),
        zipCode: z.string(),
      }),
      z.null(),
    ]),
    bankDetails: z.union([
      z.object({
        accountHolder: z.string(),
        accountNumber: z.string(),
        bankName: z.string(),
        branchName: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        updatedAt: z.iso.datetime(),
      }),
      z.null(),
    ]),
    createdAt: z.iso.datetime(),
    id: z.uuid(),
    name: z.string(),
    updatedAt: z.iso.datetime(),
  }),
  updatedAt: z.iso.datetime(),
});

export const zTransactions = z.array(
  z.object({
    collector: z.object({
      activeOrganization: z.uuid(),
      address: z.union([
        z.object({
          city: z.string(),
          country: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          lineOne: z.string(),
          lineTwo: z.union([z.string(), z.null()]),
          province: z.string(),
          updatedAt: z.iso.datetime(),
          zipCode: z.string(),
        }),
        z.null(),
      ]),
      banReason: z.union([z.string(), z.null()]),
      bankDetails: z.union([
        z.object({
          accountHolder: z.string(),
          accountNumber: z.string(),
          bankName: z.string(),
          branchName: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          updatedAt: z.iso.datetime(),
        }),
        z.null(),
      ]),
      banned: z.boolean(),
      createdAt: z.iso.datetime(),
      email: z.string(),
      id: z.uuid(),
      mfaEnabled: z.boolean(),
      mfaVerified: z.boolean(),
      name: z.string(),
      phone: z.string(),
      roles: z.array(
        z.object({
          createdAt: z.iso.datetime(),
          description: z.union([z.string(), z.null()]),
          id: z.uuid(),
          name: z.string(),
          permissions: z.array(z.string()),
          updatedAt: z.iso.datetime(),
        })
      ),
      type: z.enum(['standard', 'collector', 'business', 'system']),
      updatedAt: z.iso.datetime(),
    }),
    createdAt: z.iso.datetime(),
    id: z.uuid(),
    materials: z.array(
      z.object({
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        material: z.object({
          carbonFactor: z.string(),
          createdAt: z.iso.datetime(),
          gwCode: z.string(),
          id: z.uuid(),
          name: z.string(),
          updatedAt: z.iso.datetime(),
          value: z.number(),
        }),
        updatedAt: z.iso.datetime(),
        weight: z.number(),
      })
    ),
    organization: z.object({
      address: z.union([
        z.object({
          city: z.string(),
          country: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          lineOne: z.string(),
          lineTwo: z.union([z.string(), z.null()]),
          province: z.string(),
          updatedAt: z.iso.datetime(),
          zipCode: z.string(),
        }),
        z.null(),
      ]),
      bankDetails: z.union([
        z.object({
          accountHolder: z.string(),
          accountNumber: z.string(),
          bankName: z.string(),
          branchName: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          updatedAt: z.iso.datetime(),
        }),
        z.null(),
      ]),
      createdAt: z.iso.datetime(),
      id: z.uuid(),
      name: z.string(),
      updatedAt: z.iso.datetime(),
    }),
    updatedAt: z.iso.datetime(),
  })
);

export const zUser = z.object({
  activeOrganization: z.uuid(),
  address: z.union([
    z.object({
      city: z.string(),
      country: z.string(),
      createdAt: z.iso.datetime(),
      id: z.uuid(),
      lineOne: z.string(),
      lineTwo: z.union([z.string(), z.null()]),
      province: z.string(),
      updatedAt: z.iso.datetime(),
      zipCode: z.string(),
    }),
    z.null(),
  ]),
  banReason: z.union([z.string(), z.null()]),
  bankDetails: z.union([
    z.object({
      accountHolder: z.string(),
      accountNumber: z.string(),
      bankName: z.string(),
      branchName: z.string(),
      createdAt: z.iso.datetime(),
      id: z.uuid(),
      updatedAt: z.iso.datetime(),
    }),
    z.null(),
  ]),
  banned: z.boolean(),
  createdAt: z.iso.datetime(),
  email: z.string(),
  id: z.uuid(),
  mfaEnabled: z.boolean(),
  mfaVerified: z.boolean(),
  name: z.string(),
  phone: z.string(),
  roles: z.array(
    z.object({
      createdAt: z.iso.datetime(),
      description: z.union([z.string(), z.null()]),
      id: z.uuid(),
      name: z.string(),
      permissions: z.array(z.string()),
      updatedAt: z.iso.datetime(),
    })
  ),
  type: z.enum(['standard', 'collector', 'business', 'system']),
  updatedAt: z.iso.datetime(),
});

export const zUsers = z.array(
  z.object({
    activeOrganization: z.uuid(),
    address: z.union([
      z.object({
        city: z.string(),
        country: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        lineOne: z.string(),
        lineTwo: z.union([z.string(), z.null()]),
        province: z.string(),
        updatedAt: z.iso.datetime(),
        zipCode: z.string(),
      }),
      z.null(),
    ]),
    banReason: z.union([z.string(), z.null()]),
    bankDetails: z.union([
      z.object({
        accountHolder: z.string(),
        accountNumber: z.string(),
        bankName: z.string(),
        branchName: z.string(),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        updatedAt: z.iso.datetime(),
      }),
      z.null(),
    ]),
    banned: z.boolean(),
    createdAt: z.iso.datetime(),
    email: z.string(),
    id: z.uuid(),
    mfaEnabled: z.boolean(),
    mfaVerified: z.boolean(),
    name: z.string(),
    phone: z.string(),
    roles: z.array(
      z.object({
        createdAt: z.iso.datetime(),
        description: z.union([z.string(), z.null()]),
        id: z.uuid(),
        name: z.string(),
        permissions: z.array(z.string()),
        updatedAt: z.iso.datetime(),
      })
    ),
    type: z.enum(['standard', 'collector', 'business', 'system']),
    updatedAt: z.iso.datetime(),
  })
);

export const zGetApiAuthenticationCheckData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful authentication check.
 */
export const zGetApiAuthenticationCheckResponse = z.object({
  item: z.optional(
    z.union([
      z.object({
        activeOrganization: z.uuid(),
        address: z.union([
          z.object({
            city: z.string(),
            country: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            lineOne: z.string(),
            lineTwo: z.union([z.string(), z.null()]),
            province: z.string(),
            updatedAt: z.iso.datetime(),
            zipCode: z.string(),
          }),
          z.null(),
        ]),
        banReason: z.union([z.string(), z.null()]),
        bankDetails: z.union([
          z.object({
            accountHolder: z.string(),
            accountNumber: z.string(),
            bankName: z.string(),
            branchName: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            updatedAt: z.iso.datetime(),
          }),
          z.null(),
        ]),
        banned: z.boolean(),
        createdAt: z.iso.datetime(),
        email: z.string(),
        id: z.uuid(),
        mfaEnabled: z.boolean(),
        mfaVerified: z.boolean(),
        name: z.string(),
        phone: z.string(),
        roles: z.array(
          z.object({
            createdAt: z.iso.datetime(),
            description: z.union([z.string(), z.null()]),
            id: z.uuid(),
            name: z.string(),
            permissions: z.array(z.string()),
            updatedAt: z.iso.datetime(),
          })
        ),
        type: z.enum(['standard', 'collector', 'business', 'system']),
        updatedAt: z.iso.datetime(),
      }),
      z.object({
        createdAt: z.iso.datetime(),
        description: z.union([z.string(), z.null()]),
        id: z.uuid(),
        name: z.string(),
        permissions: z.array(z.string()),
        updatedAt: z.iso.datetime(),
      }),
      z.object({
        address: z.union([
          z.object({
            city: z.string(),
            country: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            lineOne: z.string(),
            lineTwo: z.union([z.string(), z.null()]),
            province: z.string(),
            updatedAt: z.iso.datetime(),
            zipCode: z.string(),
          }),
          z.null(),
        ]),
        bankDetails: z.union([
          z.object({
            accountHolder: z.string(),
            accountNumber: z.string(),
            bankName: z.string(),
            branchName: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            updatedAt: z.iso.datetime(),
          }),
          z.null(),
        ]),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        name: z.string(),
        updatedAt: z.iso.datetime(),
      }),
      z.union([
        z.object({
          city: z.string(),
          country: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          lineOne: z.string(),
          lineTwo: z.union([z.string(), z.null()]),
          province: z.string(),
          updatedAt: z.iso.datetime(),
          zipCode: z.string(),
        }),
        z.null(),
      ]),
      z.union([
        z.object({
          accountHolder: z.string(),
          accountNumber: z.string(),
          bankName: z.string(),
          branchName: z.string(),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          updatedAt: z.iso.datetime(),
        }),
        z.null(),
      ]),
      z.object({
        carbonFactor: z.string(),
        createdAt: z.iso.datetime(),
        gwCode: z.string(),
        id: z.uuid(),
        name: z.string(),
        updatedAt: z.iso.datetime(),
        value: z.number(),
      }),
      z.object({
        collector: z.object({
          activeOrganization: z.uuid(),
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          banReason: z.union([z.string(), z.null()]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          banned: z.boolean(),
          createdAt: z.iso.datetime(),
          email: z.string(),
          id: z.uuid(),
          mfaEnabled: z.boolean(),
          mfaVerified: z.boolean(),
          name: z.string(),
          phone: z.string(),
          roles: z.array(
            z.object({
              createdAt: z.iso.datetime(),
              description: z.union([z.string(), z.null()]),
              id: z.uuid(),
              name: z.string(),
              permissions: z.array(z.string()),
              updatedAt: z.iso.datetime(),
            })
          ),
          type: z.enum(['standard', 'collector', 'business', 'system']),
          updatedAt: z.iso.datetime(),
        }),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        materials: z.array(
          z.object({
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            material: z.object({
              carbonFactor: z.string(),
              createdAt: z.iso.datetime(),
              gwCode: z.string(),
              id: z.uuid(),
              name: z.string(),
              updatedAt: z.iso.datetime(),
              value: z.number(),
            }),
            updatedAt: z.iso.datetime(),
            weight: z.number(),
          })
        ),
        organization: z.object({
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          name: z.string(),
          updatedAt: z.iso.datetime(),
        }),
        updatedAt: z.iso.datetime(),
      }),
      z.object({
        collector: z.object({
          activeOrganization: z.uuid(),
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          banReason: z.union([z.string(), z.null()]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          banned: z.boolean(),
          createdAt: z.iso.datetime(),
          email: z.string(),
          id: z.uuid(),
          mfaEnabled: z.boolean(),
          mfaVerified: z.boolean(),
          name: z.string(),
          phone: z.string(),
          roles: z.array(
            z.object({
              createdAt: z.iso.datetime(),
              description: z.union([z.string(), z.null()]),
              id: z.uuid(),
              name: z.string(),
              permissions: z.array(z.string()),
              updatedAt: z.iso.datetime(),
            })
          ),
          type: z.enum(['standard', 'collector', 'business', 'system']),
          updatedAt: z.iso.datetime(),
        }),
        createdAt: z.iso.datetime(),
        id: z.uuid(),
        materials: z.array(
          z.object({
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            material: z.object({
              carbonFactor: z.string(),
              createdAt: z.iso.datetime(),
              gwCode: z.string(),
              id: z.uuid(),
              name: z.string(),
              updatedAt: z.iso.datetime(),
              value: z.number(),
            }),
            updatedAt: z.iso.datetime(),
            weight: z.number(),
          })
        ),
        organization: z.object({
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          name: z.string(),
          updatedAt: z.iso.datetime(),
        }),
        updatedAt: z.iso.datetime(),
      }),
    ])
  ),
  items: z.optional(
    z.union([
      z.array(
        z.object({
          activeOrganization: z.uuid(),
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          banReason: z.union([z.string(), z.null()]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          banned: z.boolean(),
          createdAt: z.iso.datetime(),
          email: z.string(),
          id: z.uuid(),
          mfaEnabled: z.boolean(),
          mfaVerified: z.boolean(),
          name: z.string(),
          phone: z.string(),
          roles: z.array(
            z.object({
              createdAt: z.iso.datetime(),
              description: z.union([z.string(), z.null()]),
              id: z.uuid(),
              name: z.string(),
              permissions: z.array(z.string()),
              updatedAt: z.iso.datetime(),
            })
          ),
          type: z.enum(['standard', 'collector', 'business', 'system']),
          updatedAt: z.iso.datetime(),
        })
      ),
      z.array(
        z.object({
          createdAt: z.iso.datetime(),
          description: z.union([z.string(), z.null()]),
          id: z.uuid(),
          name: z.string(),
          permissions: z.array(z.string()),
          updatedAt: z.iso.datetime(),
        })
      ),
      z.array(
        z.object({
          address: z.union([
            z.object({
              city: z.string(),
              country: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              lineOne: z.string(),
              lineTwo: z.union([z.string(), z.null()]),
              province: z.string(),
              updatedAt: z.iso.datetime(),
              zipCode: z.string(),
            }),
            z.null(),
          ]),
          bankDetails: z.union([
            z.object({
              accountHolder: z.string(),
              accountNumber: z.string(),
              bankName: z.string(),
              branchName: z.string(),
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              updatedAt: z.iso.datetime(),
            }),
            z.null(),
          ]),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          name: z.string(),
          updatedAt: z.iso.datetime(),
        })
      ),
      z.array(
        z.union([
          z.object({
            city: z.string(),
            country: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            lineOne: z.string(),
            lineTwo: z.union([z.string(), z.null()]),
            province: z.string(),
            updatedAt: z.iso.datetime(),
            zipCode: z.string(),
          }),
          z.null(),
        ])
      ),
      z.array(
        z.union([
          z.object({
            accountHolder: z.string(),
            accountNumber: z.string(),
            bankName: z.string(),
            branchName: z.string(),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            updatedAt: z.iso.datetime(),
          }),
          z.null(),
        ])
      ),
      z.array(
        z.object({
          carbonFactor: z.string(),
          createdAt: z.iso.datetime(),
          gwCode: z.string(),
          id: z.uuid(),
          name: z.string(),
          updatedAt: z.iso.datetime(),
          value: z.number(),
        })
      ),
      z.array(
        z.object({
          collector: z.object({
            activeOrganization: z.uuid(),
            address: z.union([
              z.object({
                city: z.string(),
                country: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                lineOne: z.string(),
                lineTwo: z.union([z.string(), z.null()]),
                province: z.string(),
                updatedAt: z.iso.datetime(),
                zipCode: z.string(),
              }),
              z.null(),
            ]),
            banReason: z.union([z.string(), z.null()]),
            bankDetails: z.union([
              z.object({
                accountHolder: z.string(),
                accountNumber: z.string(),
                bankName: z.string(),
                branchName: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                updatedAt: z.iso.datetime(),
              }),
              z.null(),
            ]),
            banned: z.boolean(),
            createdAt: z.iso.datetime(),
            email: z.string(),
            id: z.uuid(),
            mfaEnabled: z.boolean(),
            mfaVerified: z.boolean(),
            name: z.string(),
            phone: z.string(),
            roles: z.array(
              z.object({
                createdAt: z.iso.datetime(),
                description: z.union([z.string(), z.null()]),
                id: z.uuid(),
                name: z.string(),
                permissions: z.array(z.string()),
                updatedAt: z.iso.datetime(),
              })
            ),
            type: z.enum(['standard', 'collector', 'business', 'system']),
            updatedAt: z.iso.datetime(),
          }),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          materials: z.array(
            z.object({
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              material: z.object({
                carbonFactor: z.string(),
                createdAt: z.iso.datetime(),
                gwCode: z.string(),
                id: z.uuid(),
                name: z.string(),
                updatedAt: z.iso.datetime(),
                value: z.number(),
              }),
              updatedAt: z.iso.datetime(),
              weight: z.number(),
            })
          ),
          organization: z.object({
            address: z.union([
              z.object({
                city: z.string(),
                country: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                lineOne: z.string(),
                lineTwo: z.union([z.string(), z.null()]),
                province: z.string(),
                updatedAt: z.iso.datetime(),
                zipCode: z.string(),
              }),
              z.null(),
            ]),
            bankDetails: z.union([
              z.object({
                accountHolder: z.string(),
                accountNumber: z.string(),
                bankName: z.string(),
                branchName: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                updatedAt: z.iso.datetime(),
              }),
              z.null(),
            ]),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            name: z.string(),
            updatedAt: z.iso.datetime(),
          }),
          updatedAt: z.iso.datetime(),
        })
      ),
      z.array(
        z.object({
          collector: z.object({
            activeOrganization: z.uuid(),
            address: z.union([
              z.object({
                city: z.string(),
                country: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                lineOne: z.string(),
                lineTwo: z.union([z.string(), z.null()]),
                province: z.string(),
                updatedAt: z.iso.datetime(),
                zipCode: z.string(),
              }),
              z.null(),
            ]),
            banReason: z.union([z.string(), z.null()]),
            bankDetails: z.union([
              z.object({
                accountHolder: z.string(),
                accountNumber: z.string(),
                bankName: z.string(),
                branchName: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                updatedAt: z.iso.datetime(),
              }),
              z.null(),
            ]),
            banned: z.boolean(),
            createdAt: z.iso.datetime(),
            email: z.string(),
            id: z.uuid(),
            mfaEnabled: z.boolean(),
            mfaVerified: z.boolean(),
            name: z.string(),
            phone: z.string(),
            roles: z.array(
              z.object({
                createdAt: z.iso.datetime(),
                description: z.union([z.string(), z.null()]),
                id: z.uuid(),
                name: z.string(),
                permissions: z.array(z.string()),
                updatedAt: z.iso.datetime(),
              })
            ),
            type: z.enum(['standard', 'collector', 'business', 'system']),
            updatedAt: z.iso.datetime(),
          }),
          createdAt: z.iso.datetime(),
          id: z.uuid(),
          materials: z.array(
            z.object({
              createdAt: z.iso.datetime(),
              id: z.uuid(),
              material: z.object({
                carbonFactor: z.string(),
                createdAt: z.iso.datetime(),
                gwCode: z.string(),
                id: z.uuid(),
                name: z.string(),
                updatedAt: z.iso.datetime(),
                value: z.number(),
              }),
              updatedAt: z.iso.datetime(),
              weight: z.number(),
            })
          ),
          organization: z.object({
            address: z.union([
              z.object({
                city: z.string(),
                country: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                lineOne: z.string(),
                lineTwo: z.union([z.string(), z.null()]),
                province: z.string(),
                updatedAt: z.iso.datetime(),
                zipCode: z.string(),
              }),
              z.null(),
            ]),
            bankDetails: z.union([
              z.object({
                accountHolder: z.string(),
                accountNumber: z.string(),
                bankName: z.string(),
                branchName: z.string(),
                createdAt: z.iso.datetime(),
                id: z.uuid(),
                updatedAt: z.iso.datetime(),
              }),
              z.null(),
            ]),
            createdAt: z.iso.datetime(),
            id: z.uuid(),
            name: z.string(),
            updatedAt: z.iso.datetime(),
          }),
          updatedAt: z.iso.datetime(),
        })
      ),
    ])
  ),
  pageDetails: z.optional(
    z.union([
      z.object({
        count: z.optional(z.int().gte(0)),
        currentPage: z.optional(z.int().gte(1)),
        nextPage: z.optional(z.int().gte(2)),
        pages: z.optional(z.int().gte(0)),
        previousPage: z.optional(z.int().gte(1)),
      }),
      z.null(),
    ])
  ),
});

export const zPostApiAuthenticationLoginData = z.object({
  body: z.object({
    emailOrPhone: z.email(),
    password: z.string().min(6).max(100),
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiAuthenticationLogoutData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiAuthenticationMfaEnableData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPostApiAuthenticationMfaVerifyData = z.object({
  body: z.object({
    code: z.optional(z.string()),
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiMaterialsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.coerce.bigint().gte(BigInt(1))).default(BigInt(1)),
      limit: z.optional(z.coerce.bigint().gte(BigInt(10))).default(BigInt(10)),
      search: z.optional(z.string()),
    })
  ),
});

/**
 * Successful materials retrieval.
 */
export const zGetApiMaterialsResponse = z.array(
  z.object({
    carbonFactor: z.string(),
    createdAt: z.iso.datetime(),
    gwCode: z.string(),
    id: z.uuid(),
    name: z.string(),
    updatedAt: z.iso.datetime(),
    value: z.number(),
  })
);

export const zPostApiMaterialsData = z.object({
  body: z.object({
    carbonFactor: z.number(),
    gwCode: z.string(),
    name: z.string(),
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful material creation.
 */
export const zPostApiMaterialsResponse = z.string();

export const zDeleteApiMaterialsByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful material deletion.
 */
export const zDeleteApiMaterialsByIdResponse = z.string();

export const zGetApiMaterialsByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful material retrieval.
 */
export const zGetApiMaterialsByIdResponse = z.object({
  carbonFactor: z.string(),
  createdAt: z.iso.datetime(),
  gwCode: z.string(),
  id: z.uuid(),
  name: z.string(),
  updatedAt: z.iso.datetime(),
  value: z.number(),
});

export const zPatchApiMaterialsByIdData = z.object({
  body: z.object({
    carbonFactor: z.optional(z.number()),
    gwCode: z.optional(z.string()),
    name: z.optional(z.string()),
  }),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful material update.
 */
export const zPatchApiMaterialsByIdResponse = z.string();
