/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthRolesIndexRouteImport } from './routes/_auth/roles/index'
import { Route as AuthMaterialsIndexRouteImport } from './routes/_auth/materials/index'
import { Route as AuthCollectionsIndexRouteImport } from './routes/_auth/collections/index'
import { Route as AuthUsersCreateRouteImport } from './routes/_auth/users/create'
import { Route as AuthRolesCreateRouteImport } from './routes/_auth/roles/create'
import { Route as AuthMaterialsCreateRouteImport } from './routes/_auth/materials/create'
import { Route as AuthCollectionsCreateRouteImport } from './routes/_auth/collections/create'
import { Route as AuthUsersIdIndexRouteImport } from './routes/_auth/users/$id/index'
import { Route as AuthRolesIdIndexRouteImport } from './routes/_auth/roles/$id/index'
import { Route as AuthMaterialsIdIndexRouteImport } from './routes/_auth/materials/$id/index'
import { Route as AuthCollectionsIdIndexRouteImport } from './routes/_auth/collections/$id/index'
import { Route as AuthUsersIdEditRouteImport } from './routes/_auth/users/$id/edit'
import { Route as AuthRolesIdPermissionsRouteImport } from './routes/_auth/roles/$id/permissions'
import { Route as AuthRolesIdEditRouteImport } from './routes/_auth/roles/$id/edit'
import { Route as AuthMaterialsIdEditRouteImport } from './routes/_auth/materials/$id/edit'
import { Route as AuthCollectionsIdEditRouteImport } from './routes/_auth/collections/$id/edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesIndexRoute = AuthRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMaterialsIndexRoute = AuthMaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCollectionsIndexRoute = AuthCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersCreateRoute = AuthUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesCreateRoute = AuthRolesCreateRouteImport.update({
  id: '/roles/create',
  path: '/roles/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMaterialsCreateRoute = AuthMaterialsCreateRouteImport.update({
  id: '/materials/create',
  path: '/materials/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCollectionsCreateRoute = AuthCollectionsCreateRouteImport.update({
  id: '/collections/create',
  path: '/collections/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIdIndexRoute = AuthUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesIdIndexRoute = AuthRolesIdIndexRouteImport.update({
  id: '/roles/$id/',
  path: '/roles/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMaterialsIdIndexRoute = AuthMaterialsIdIndexRouteImport.update({
  id: '/materials/$id/',
  path: '/materials/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCollectionsIdIndexRoute = AuthCollectionsIdIndexRouteImport.update({
  id: '/collections/$id/',
  path: '/collections/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIdEditRoute = AuthUsersIdEditRouteImport.update({
  id: '/users/$id/edit',
  path: '/users/$id/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesIdPermissionsRoute = AuthRolesIdPermissionsRouteImport.update({
  id: '/roles/$id/permissions',
  path: '/roles/$id/permissions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesIdEditRoute = AuthRolesIdEditRouteImport.update({
  id: '/roles/$id/edit',
  path: '/roles/$id/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMaterialsIdEditRoute = AuthMaterialsIdEditRouteImport.update({
  id: '/materials/$id/edit',
  path: '/materials/$id/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCollectionsIdEditRoute = AuthCollectionsIdEditRouteImport.update({
  id: '/collections/$id/edit',
  path: '/collections/$id/edit',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-up': typeof SignUpRoute
  '/': typeof AuthIndexRoute
  '/collections/create': typeof AuthCollectionsCreateRoute
  '/materials/create': typeof AuthMaterialsCreateRoute
  '/roles/create': typeof AuthRolesCreateRoute
  '/users/create': typeof AuthUsersCreateRoute
  '/collections': typeof AuthCollectionsIndexRoute
  '/materials': typeof AuthMaterialsIndexRoute
  '/roles': typeof AuthRolesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/collections/$id/edit': typeof AuthCollectionsIdEditRoute
  '/materials/$id/edit': typeof AuthMaterialsIdEditRoute
  '/roles/$id/edit': typeof AuthRolesIdEditRoute
  '/roles/$id/permissions': typeof AuthRolesIdPermissionsRoute
  '/users/$id/edit': typeof AuthUsersIdEditRoute
  '/collections/$id': typeof AuthCollectionsIdIndexRoute
  '/materials/$id': typeof AuthMaterialsIdIndexRoute
  '/roles/$id': typeof AuthRolesIdIndexRoute
  '/users/$id': typeof AuthUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-up': typeof SignUpRoute
  '/': typeof AuthIndexRoute
  '/collections/create': typeof AuthCollectionsCreateRoute
  '/materials/create': typeof AuthMaterialsCreateRoute
  '/roles/create': typeof AuthRolesCreateRoute
  '/users/create': typeof AuthUsersCreateRoute
  '/collections': typeof AuthCollectionsIndexRoute
  '/materials': typeof AuthMaterialsIndexRoute
  '/roles': typeof AuthRolesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/collections/$id/edit': typeof AuthCollectionsIdEditRoute
  '/materials/$id/edit': typeof AuthMaterialsIdEditRoute
  '/roles/$id/edit': typeof AuthRolesIdEditRoute
  '/roles/$id/permissions': typeof AuthRolesIdPermissionsRoute
  '/users/$id/edit': typeof AuthUsersIdEditRoute
  '/collections/$id': typeof AuthCollectionsIdIndexRoute
  '/materials/$id': typeof AuthMaterialsIdIndexRoute
  '/roles/$id': typeof AuthRolesIdIndexRoute
  '/users/$id': typeof AuthUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/collections/create': typeof AuthCollectionsCreateRoute
  '/_auth/materials/create': typeof AuthMaterialsCreateRoute
  '/_auth/roles/create': typeof AuthRolesCreateRoute
  '/_auth/users/create': typeof AuthUsersCreateRoute
  '/_auth/collections/': typeof AuthCollectionsIndexRoute
  '/_auth/materials/': typeof AuthMaterialsIndexRoute
  '/_auth/roles/': typeof AuthRolesIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/collections/$id/edit': typeof AuthCollectionsIdEditRoute
  '/_auth/materials/$id/edit': typeof AuthMaterialsIdEditRoute
  '/_auth/roles/$id/edit': typeof AuthRolesIdEditRoute
  '/_auth/roles/$id/permissions': typeof AuthRolesIdPermissionsRoute
  '/_auth/users/$id/edit': typeof AuthUsersIdEditRoute
  '/_auth/collections/$id/': typeof AuthCollectionsIdIndexRoute
  '/_auth/materials/$id/': typeof AuthMaterialsIdIndexRoute
  '/_auth/roles/$id/': typeof AuthRolesIdIndexRoute
  '/_auth/users/$id/': typeof AuthUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-up'
    | '/'
    | '/collections/create'
    | '/materials/create'
    | '/roles/create'
    | '/users/create'
    | '/collections'
    | '/materials'
    | '/roles'
    | '/users'
    | '/collections/$id/edit'
    | '/materials/$id/edit'
    | '/roles/$id/edit'
    | '/roles/$id/permissions'
    | '/users/$id/edit'
    | '/collections/$id'
    | '/materials/$id'
    | '/roles/$id'
    | '/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-up'
    | '/'
    | '/collections/create'
    | '/materials/create'
    | '/roles/create'
    | '/users/create'
    | '/collections'
    | '/materials'
    | '/roles'
    | '/users'
    | '/collections/$id/edit'
    | '/materials/$id/edit'
    | '/roles/$id/edit'
    | '/roles/$id/permissions'
    | '/users/$id/edit'
    | '/collections/$id'
    | '/materials/$id'
    | '/roles/$id'
    | '/users/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/sign-up'
    | '/_auth/'
    | '/_auth/collections/create'
    | '/_auth/materials/create'
    | '/_auth/roles/create'
    | '/_auth/users/create'
    | '/_auth/collections/'
    | '/_auth/materials/'
    | '/_auth/roles/'
    | '/_auth/users/'
    | '/_auth/collections/$id/edit'
    | '/_auth/materials/$id/edit'
    | '/_auth/roles/$id/edit'
    | '/_auth/roles/$id/permissions'
    | '/_auth/users/$id/edit'
    | '/_auth/collections/$id/'
    | '/_auth/materials/$id/'
    | '/_auth/roles/$id/'
    | '/_auth/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles/': {
      id: '/_auth/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthRolesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/materials/': {
      id: '/_auth/materials/'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthMaterialsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/collections/': {
      id: '/_auth/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthCollectionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/create': {
      id: '/_auth/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthUsersCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles/create': {
      id: '/_auth/roles/create'
      path: '/roles/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof AuthRolesCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/materials/create': {
      id: '/_auth/materials/create'
      path: '/materials/create'
      fullPath: '/materials/create'
      preLoaderRoute: typeof AuthMaterialsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/collections/create': {
      id: '/_auth/collections/create'
      path: '/collections/create'
      fullPath: '/collections/create'
      preLoaderRoute: typeof AuthCollectionsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/$id/': {
      id: '/_auth/users/$id/'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthUsersIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles/$id/': {
      id: '/_auth/roles/$id/'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof AuthRolesIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/materials/$id/': {
      id: '/_auth/materials/$id/'
      path: '/materials/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof AuthMaterialsIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/collections/$id/': {
      id: '/_auth/collections/$id/'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AuthCollectionsIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/$id/edit': {
      id: '/_auth/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof AuthUsersIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles/$id/permissions': {
      id: '/_auth/roles/$id/permissions'
      path: '/roles/$id/permissions'
      fullPath: '/roles/$id/permissions'
      preLoaderRoute: typeof AuthRolesIdPermissionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles/$id/edit': {
      id: '/_auth/roles/$id/edit'
      path: '/roles/$id/edit'
      fullPath: '/roles/$id/edit'
      preLoaderRoute: typeof AuthRolesIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/materials/$id/edit': {
      id: '/_auth/materials/$id/edit'
      path: '/materials/$id/edit'
      fullPath: '/materials/$id/edit'
      preLoaderRoute: typeof AuthMaterialsIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/collections/$id/edit': {
      id: '/_auth/collections/$id/edit'
      path: '/collections/$id/edit'
      fullPath: '/collections/$id/edit'
      preLoaderRoute: typeof AuthCollectionsIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCollectionsCreateRoute: typeof AuthCollectionsCreateRoute
  AuthMaterialsCreateRoute: typeof AuthMaterialsCreateRoute
  AuthRolesCreateRoute: typeof AuthRolesCreateRoute
  AuthUsersCreateRoute: typeof AuthUsersCreateRoute
  AuthCollectionsIndexRoute: typeof AuthCollectionsIndexRoute
  AuthMaterialsIndexRoute: typeof AuthMaterialsIndexRoute
  AuthRolesIndexRoute: typeof AuthRolesIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthCollectionsIdEditRoute: typeof AuthCollectionsIdEditRoute
  AuthMaterialsIdEditRoute: typeof AuthMaterialsIdEditRoute
  AuthRolesIdEditRoute: typeof AuthRolesIdEditRoute
  AuthRolesIdPermissionsRoute: typeof AuthRolesIdPermissionsRoute
  AuthUsersIdEditRoute: typeof AuthUsersIdEditRoute
  AuthCollectionsIdIndexRoute: typeof AuthCollectionsIdIndexRoute
  AuthMaterialsIdIndexRoute: typeof AuthMaterialsIdIndexRoute
  AuthRolesIdIndexRoute: typeof AuthRolesIdIndexRoute
  AuthUsersIdIndexRoute: typeof AuthUsersIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthCollectionsCreateRoute: AuthCollectionsCreateRoute,
  AuthMaterialsCreateRoute: AuthMaterialsCreateRoute,
  AuthRolesCreateRoute: AuthRolesCreateRoute,
  AuthUsersCreateRoute: AuthUsersCreateRoute,
  AuthCollectionsIndexRoute: AuthCollectionsIndexRoute,
  AuthMaterialsIndexRoute: AuthMaterialsIndexRoute,
  AuthRolesIndexRoute: AuthRolesIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthCollectionsIdEditRoute: AuthCollectionsIdEditRoute,
  AuthMaterialsIdEditRoute: AuthMaterialsIdEditRoute,
  AuthRolesIdEditRoute: AuthRolesIdEditRoute,
  AuthRolesIdPermissionsRoute: AuthRolesIdPermissionsRoute,
  AuthUsersIdEditRoute: AuthUsersIdEditRoute,
  AuthCollectionsIdIndexRoute: AuthCollectionsIdIndexRoute,
  AuthMaterialsIdIndexRoute: AuthMaterialsIdIndexRoute,
  AuthRolesIdIndexRoute: AuthRolesIdIndexRoute,
  AuthUsersIdIndexRoute: AuthUsersIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
